/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns the health status of the server
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Server is healthy */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HealthResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all invocations
         * @description Returns a list of all agent invocations, sorted by most recent first
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of invocations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invocation"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invocations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get invocation by ID
         * @description Returns a single invocation by its ID
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invocation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Invocation found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Invocation"];
                    };
                };
                /** @description Invocation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invocations/{id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get invocation messages
         * @description Returns all messages for a specific invocation
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Invocation ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List of messages */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["InvocationMessage"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhook/gitlab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * GitLab webhook endpoint
         * @description Receives GitLab webhook events and triggers agent invocations based on configured rules
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["GitLabWebhookPayload"];
                };
            };
            responses: {
                /** @description Webhook processed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookAcceptedResponse"] | components["schemas"]["WebhookIgnoredResponse"];
                    };
                };
                /** @description Unauthorized - invalid or missing X-Gitlab-Token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WebhookUnauthorizedResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        Invocation: {
            id: string;
            /** @enum {string} */
            status: "running" | "completed" | "failed";
            prompt: string;
            cwd: string;
            startedAt: string;
            completedAt?: string;
            result?: string;
            error?: string;
            durationMs?: number;
            totalCostUsd?: number;
            numTurns?: number;
            model?: string;
        };
        ErrorResponse: {
            error: string;
        };
        InvocationMessage: {
            timestamp: string;
            type: string;
            text?: string;
            raw?: unknown;
        };
        WebhookAcceptedResponse: {
            /** @enum {string} */
            status: "accepted";
            matched_rule: {
                label: string;
                prompt: string;
            };
        };
        WebhookIgnoredResponse: {
            /** @enum {string} */
            status: "ignored";
            reason: string;
        };
        WebhookUnauthorizedResponse: {
            /** @enum {string} */
            error: "Unauthorized";
        };
        GitLabWebhookPayload: {
            object_kind: string;
            object_attributes?: {
                action?: string;
                labels?: {
                    title: string;
                }[];
            };
            labels?: {
                title: string;
            }[];
            changes?: {
                labels?: {
                    previous?: {
                        title: string;
                    }[];
                    current?: {
                        title: string;
                    }[];
                };
            };
            project?: {
                path_with_namespace?: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
