stages:
  - check

calculator:
  stage: check
  image: oven/bun:latest
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes:
        - examples/calculator/**/*
  script:
    - cd examples/calculator
    - bun install
    - bun run build
    - bun test
