image: oven/bun:latest

stages:
  - check

install:
  stage: .pre
  script:
    - bun install --frozen-lockfile
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/

typecheck:
  stage: check
  script:
    - bun install --frozen-lockfile
    - bun run typecheck
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull

build:
  stage: check
  script:
    - bun install --frozen-lockfile
    - bun run build
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull

test:
  stage: check
  script:
    - bun install --frozen-lockfile
    - bun run test
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - node_modules/
    policy: pull
